### ISSUE TITLE
Animation not working with nested layout

### ISSUE THREAD

**Issue by ibhavikmakwana** [ibhavikmakwana/Constraint-Layout-Animations#2]
- Animation is not working when using the nesting of the layouts in the [ShoppingKeyFrameAnimation](https://github.com/ibhavikmakwana/Constraint-Layout-Animations/blob/master/app/src/main/java/com/keyframeanimationdemo/ShoppingKeyFrameAnimation.kt)

**Comment by LoveqLRC** [comment]
Hope to fix it

**Comment by ibhavikmakwana** [comment]
I have fixed the bug just did not get the time to change the UI and other stuff will update it soon 👍

**Comment by ibhavikmakwana** [comment]
- Fixed the animation not working inside the card layout (nested layout)
